### ISSUE TITLE
 SSIM calculated

### ISSUE THREAD

**Issue by 2ZiZ2** [Arksyd96/synthesis-with-slice-based-ldm#3]
Hello, dear.
I am a university student interested in diffusion modelling.
I have a few questions about your model:
Firstly: When training the second step, the generated image and the corresponding mask are recorded in WandB, I want to verify the performance of the second step is good or bad, can I only view the loss? Can I show the results of the generated image compared to the source image as in the first step of training?
Secondly, what are the evaluation criteria such as SSIM calculated in the table in your article? If it is the SSIM of the original image and the generated image, which one is the original image? Which one does the generated image correspond to?

**Comment by Arksyd96** [comment]
When dealing with generative models, you can use SSIM to compare a real set of images and a fake set of images (generated).

If the set is enough large, it should return you a good approximation of how much your fake images are realistic. This applies also to metrics such as FID, LPIPS, however those are not available in 3D, thus making evaluation of 3D images difficult.

**Comment by 2ZiZ2** [comment]
Dear, are you calculating SSIM using a 2D slice?
