### ISSUE TITLE
TypeError: VAE.__init__() got an unexpected keyword argument 'precision' in first_stage_training.py

### ISSUE THREAD

**Issue by HeiHill** [Arksyd96/synthesis-with-slice-based-ldm#4]
**Description:**

Hello,

I encountered an issue when running the script `first_stage_training.py`. The error message suggests that the VAE class does not accept a precision argument during initialization:

```python
Traceback (most recent call last):
  File "/synthesis-with-slice-based-ldm/first_stage_training.py", line 51, in <module>
    model = VAE(
            ^^^^
TypeError: VAE.__init__() got an unexpected keyword argument 'precision'
```

After inspecting the VAE class definition, it seems that precision is not defined as an argument:

```python
class VAE(BasicModel):
    def __init__(
        self,
        in_channels = 3, 
        out_channels = 3, 
        spatial_dims = 2,
        emb_channels = 4,
        hid_chs = [64, 128, 256, 512],
        kernel_sizes = [3, 3, 3, 3],
        strides = [1, 2, 2, 2],
        norm_name = ("GROUP", {'num_groups':8, "affine": True}),
        act_name = ("Swish", {}),
        time_embedder = None,
        time_embedder_kwargs = {}, 
        dropout = None,
        use_res_block = True,
        deep_supervision = False,
        learnable_interpolation = True,
        use_attention = 'none',
        embedding_loss_weight = 1e-6,
        perceiver = LPIPS, 
        perceiver_kwargs = {},
        perceptual_loss_weight = 1.0,
        optimizer = torch.optim.Adam, 
        optimizer_kwargs = {'lr':1e-4},
        lr_scheduler = None, 
        lr_scheduler_kwargs = {},
        loss = torch.nn.L1Loss,
        loss_kwargs = {'reduction': 'none'},
        use_ssim_loss = True,
        use_perceptual_loss = True,
        sample_every_n_steps = 1000
    ):

```

It seems like either:

1. The precision parameter needs to be removed from the VAE instantiation in `first_stage_training.py`, or
2. The VAE class should be updated to accept the precision parameter if it's meant to handle it directly.

Would you be able to clarify the intended functionality?

Thank you!

**Comment by Arksyd96** [comment]
Hello HeiHill,

You're absolutely right; there's an error in `first_stage_training.py`. You should remove the `precision=32` argument from the model instantiation. The model was originally implemented as an nn.Module and handled precision manually, later transitioned to `pl.LightningModule`, which manages precision automatically, but I forgot to adjust this in the code.

I'll update the repository with a cleaner and more refined version soon, once I have some free time. Please note that this implementation is not entirely mine, I had to move quick and took inspiration from this repository: https://github.com/mueller-franzes/medfusion.

Thanks for catching that! And take a look to the original code for a deeper understanding of the architecture.
